[build]
  command = "npm run netlify:build"
  publish = ".next"

[plugins]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
  PRISMA_CLI_BINARY_TARGETS = "native,rhel-openssl-3.0.x"
